language: swift
osx_image: xcode9.3

before_install:
  - gem install cocoapods
  - pod --version

script:
  - pod repo update && pod update
  - set -o pipefail
  - xcodebuild build test -workspace Splashy.xcworkspace -scheme Splashy -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
