language: swift
osx_image: xcode9.3

before_install:
  - gem install cocoapods
  - pod --version

script:
  - pod repo update && pod update
  - set -o pipefail
  - xcodebuild -workspace Splashy.xcworkspace -scheme Splashy -destination "platform=iOS Simulator,name=iPhone 8,OS=11.3" CODE_SIGNING_REQUIRED=NO  build test| xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
